#ifndef __LIBRARIES__H__
#define __LIBRARIES__H__
#include <iostream>
#include <vector>
#include <map>
#include <algorithm>
#include <csignal>
#include <readline/readline.h>
#include <readline/history.h>
#include <unistd.h>
#include <math.h>
#endif  //!__LIBRARIES__H__
